name: yarn2nix
version: 0.10.1
github: Profpatsch/yarn2nix
license: MIT
license-file: LICENSE
synopsis: Convert yarn.lock files to nix expressions
description: Convert @yarn.lock@ files to nix expressions. See @yarn2nix@ executable. Contains a nix library to call the generated nix files in @nix-lib/@. Library functions and module names might be restructured in the future.
author: Profpatsch
maintainer: mail@profpatsch.de
category: Distribution, Nix

extra-source-files:
  - LICENSE
  - README.md
  - nix-lib/*

ghc-options:
  - -Wall

dependencies:
  - aeson >= 2.0
  - aeson-better-errors >= 0.9.1.1
  - async-pool == 0.9.*
  - base == 4.*
  - bytestring >= 0.10 && < 0.12
  - containers >= 0.5 && < 0.7
  - data-fix >= 0.0.7 && < 0.4
  - directory == 1.3.*
  - filepath == 1.4.*
  - hnix >= 0.6 && < 0.17
  - mtl == 2.2.*
  - prettyprinter >= 1.2 && < 1.8
  - process >= 1.4
  - protolude ^>= 0.3
  - regex-tdfa ^>= 1.3
  - stm > 2.4.0 && < 2.6.0.0
  - scientific > 0.3.3.0 && < 0.4
  - text == 1.2.*
  - transformers == 0.5.*
  - unordered-containers == 0.2.*
  - yarn-lock == 0.6.*
  - optparse-applicative >= 0.16 && < 0.18

library:
  source-dirs: src

executables:
  yarn2nix:
    main: Main.hs
    dependencies:
      - yarn2nix
  node-package-tool:
    main: NodePackageTool.hs
    dependencies:
      - optparse-applicative >= 0.13
      - unix == 2.7.*
      - yarn2nix

tests:
  yarn2nix-tests:
    main: Test.hs
    source-dirs: tests
    dependencies:
      - neat-interpolation >= 0.3 && < 0.6
      - protolude ^>= 0.3
      - tasty >= 0.11 && < 1.5
      - tasty-hunit >= 0.9 && < 0.11
      - tasty-quickcheck >= 0.8 && < 0.11
      - tasty-th == 0.1.7.*
      - yarn2nix
