# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  nix-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: nixery.dev/shell/nix

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: cachix/cachix-action@v6
      with:
        name: yarn2nix
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    # Runs a single command using the runners shell
    - name: Build nix-tests
      run: env NIX_PATH= nix-build tests/nix-tests/default.nix
