# this is a file that has the same interface
# as the files generated by yarn2nix, but uses
# local files instead of downloading them
{ fetchurl, fetchgit }:
self: super:

let
  buildNodePackage = super._buildNodePackage;

  localFilePackage = name: version: path: deps:
    buildNodePackage {
      inherit name version;
      nodeBuildInputs = deps;
      src = path;
    };

in {
  "left-pad" = localFilePackage "left-pad" "0.1.2" ./left-pad [];
}
