{ pkgs, nixLib, yarn2nix }:

# A very simple sanity check:
# a nodePackage without contents based
# on a deps file and a template file
# generated by yarn2nix should evaluate
# and build correctly.

let
  src = ./top-pad;
  npmDeps = nixLib.buildCallDeps {
    yarnLock = src + /yarn.lock;
  };
  npmPackage = nixLib.buildTemplate {
    packageJson = src + /package.json;
  };
in
nixLib.buildNodePackage ({
  src = nixLib.removePrefixes [ "node_modules" ] src;
} // nixLib.callTemplate npmPackage (nixLib.buildNodeDeps npmDeps))
